### ISSUE TITLE
Add a logo for the TypeScript language.

### ISSUE THREAD

**Issue by tacosontitan** [tacosontitan/Hazel.js#3]
A logo for TypeScript is needed in the `languages.json` file:

https://github.com/tacosontitan/Hazel.js/blob/8b870c77ecb2bc84b0f65514a8cc31ace831194e/data/languages.json#L12-L16

**Comment by pgmtx** [comment]
Is it okay to use absolute link like [that one](https://upload.wikimedia.org/wikipedia/commons/f/f5/Typescript.svg) ?

**Comment by tacosontitan** [comment]
That's fine by me 🙂

**Comment by pgmtx** [comment]
Okay, then I'll take care of it
